#!/bin/sh
num=0
count=0
cd ..
make
mv cub3D tester
make clean
cd tester
> out
echo "\n"
echo "               #############################"
echo "               ##### Cube Input Tester #####"
echo "               #############################\n"
echo "       loading......        50%     just asking cats...."
ft_test()
{
    count=$((count+1))
    echo "\n-> Test $count:" >> out
    ./cub3D $1 >> out 2>&1
    valgrind ./cub3D $1 > valgrind_test.txt 2>&1
    grep -q "ERROR SUMMARY: 0 errors" valgrind_test.txt
    val_error=$?
    grep -q "All heap blocks were freed -- no leaks are possible" valgrind_test.txt
    val_blocks=$?
    num=$(($num + $val_error + $val_blocks))
    if [ $num -ne 0 ]
        then echo valgrind error @ $1
    fi
    echo -n "🐱"
}

ft_test
ft_test empty.cub
ft_test hi.cub
ft_test t1.cub
ft_test t2.cub
ft_test t3.cub
ft_test t4.cub
ft_test t5.cub
ft_test t6.cub
ft_test t7.cub
ft_test t8.cub
ft_test t9.cub
ft_test t10.cub
ft_test t11.cub
ft_test t12.cub
ft_test t13.cub
ft_test t14.cub
ft_test t15.cub
ft_test t16.cub
ft_test t17.cub
ft_test t18.cub
ft_test t19.cub
ft_test t20.cub
ft_test t21.cub
ft_test t22.cub
ft_test t23.cub
ft_test t24.cub
ft_test t25.cub

if [ $num -eq 0 ]
    then echo -n "\n\nvalgrind: ok 😻 | "
else
    echo -n "\nvalgrind: ko 🙀 | "
fi

diff out in

if [ $? -eq 0 ]
    then echo -n "tests:    ok 😽\n"
    rm out valgrind_test.txt
else
    echo -n tests: ko 🙀
fi