#!/bin/sh
num=0
cd ..
make
mv cub3D tester
make clean
cd tester
> out
ft_test()
{
    ./cub3D $1 >> out 2>&1
    valgrind ./cub3D $1 > valgrind_test.txt 2>&1
    grep -q "ERROR SUMMARY: 0 errors" valgrind_test.txt
    val_error=$?
    grep -q "All heap blocks were freed -- no leaks are possible" valgrind_test.txt
    val_blocks=$?
    num=$(($num + $val_error + $val_blocks))
    if [ $num -ne 0 ]
        then echo valgrind error @ $1
    fi
}

ft_test empty.cub
ft_test t1.cub
ft_test t2.cub
ft_test t3.cub
ft_test t4.cub
ft_test t5.cub

if [ $num -eq 0 ]
    then echo valgrind: ok
else
    echo valgrind: ko
fi

diff out in

if [ $? -eq 0 ]
    then echo "tests:    ok"
    rm out valgrind_test.txt
else
    echo ko
fi